name: Deploy to S3

on:
    push:
        branches:
            - develop

# OIDCトークン取得に必要な権限
permissions:
  id-token: write   # OIDCトークンを取得するために必要
  contents: read    # リポジトリのコンテンツを読み取るために必要

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        # OIDC経由でAWSクレデンシャルを設定
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-S3Deploy-Role
            role-session-name: GitHubActionsSession
            aws-region: ${{ secrets.AWS_REGION }}
      
        - name: Upload to S3
          run: |
            aws s3 cp contents/profile-website.html s3://${{ secrets.S3_BUCKET_NAME }}/profile-website.html \
                --content-type "text/html; charset=utf-8"
      
        - name: Invalidate CloudFront
          run: |
            aws cloudfront create-invalidation \
                --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                --paths "/profile-website.html"
